Name:           ros-kinetic-rocon-multimaster
Version:        0.8.1
Release:        2%{?dist}
Summary:        ROS rocon_multimaster package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rocon_multimaster
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-rocon-gateway
Requires:       ros-kinetic-rocon-gateway-tests
Requires:       ros-kinetic-rocon-gateway-utils
Requires:       ros-kinetic-rocon-hub
Requires:       ros-kinetic-rocon-hub-client
Requires:       ros-kinetic-rocon-test
Requires:       ros-kinetic-rocon-unreliable-experiments
BuildRequires:  ros-kinetic-catkin

%description
This doesn't do everything you need for multimaster, however it does provide the
building blocks common to most or all multimaster systems. In particular, it
provides the gateway model, which is an upgrade on old foreign_relay and
master_sync concepts.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Oct 12 2016 Daniel Stonier <d.stonier@gmail.com> - 0.8.1-2
- Autogenerated by Bloom

* Tue Jun 21 2016 Daniel Stonier <d.stonier@gmail.com> - 0.8.1-1
- Autogenerated by Bloom

* Tue Jun 21 2016 Daniel Stonier <d.stonier@gmail.com> - 0.8.1-0
- Autogenerated by Bloom

